random_names = ["Flora Green",
                "Anthony Griffin",
                "Charlie Smith",
                "Liam Combs",
                "Irene Dougherty",
                "Brett Hardin",
                "Vada Barber",
                "Solomon Rose",
                "Magnolia Sampson",
                "Cain Yu",
                "Navy Jefferson",
                "Raylan Hayden",
                "Avayah Pruitt",
                "Gatlin Khan",
                "Mabel McIntyre",
                "Eliseo Page",
                "Cataleya Mayo",
                ]

random_cities = ["Bonn",
                 "Köln",
                 "Hamburg",
                 "Berlin",
                 "München",
                 "Tirol",
                 "Bochum",
                 "Dortmund",
                 "Düsseldorf",
]
